services:

    db:
        image: postgres
        ports:
            - "127.0.0.1:5432:5432"
            - "[::1]:5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: qazxswedc
            POSTGRES_DB: edu
        volumes:
            - pgdata:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
            - "127.0.0.1:8000:8080"
            - "[::1]:8000:8080"

volumes:
    pgdata:
